// import { Geist, Geist_Mono, Urbanist, Poppins, Work_Sans,Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/organisms/Header";
// import Footer from "@/components/organisms/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// const urbanist = Urbanist({
//   variable: "--font-urbanist",
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// const workSans = Work_Sans({
//   variable: "--font-work-sans",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// export const metadata = {
//   title: "store panel",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`
//           ${geistSans.variable}
//           ${inter.variable}
//           ${geistMono.variable}
//           ${urbanist.variable}
//           ${poppins.variable}
//           ${workSans.variable}
//           antialiased
//         `}
//       >
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }



import { Urbanist, Poppins, Work_Sans, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "store panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable}
          ${urbanist.variable}
          ${poppins.variable}
          ${workSans.variable}
          antialiased
        `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
